# MG-RAST API base image (mgrast/api-base)

# docker build -t mgrast/api-base -f Dockerfile_api-base .

FROM httpd:2.4


# MG-RAST dependencies
RUN apt-get update && apt-get install -y \
  make \
  curl \
  ncbi-blast+ \
  perl-modules \
  liburi-perl \
  liburi-encode-perl \
  libwww-perl \
  libjson-perl \
  libdbi-perl \
  libdbd-mysql-perl \
  libdigest-md5-perl \
  libfile-slurp-perl \
  libhtml-strip-perl \
  liblist-moreutils-perl \
  libcache-memcached-perl \
  libhtml-template-perl \
  libdigest-md5-perl \
  libdigest-md5-file-perl \
  libdatetime-perl \
  libdatetime-format-ISO8601-perl \
  liblist-allutils-perl \
  libposix-strptime-perl \
  libuuid-tiny-perl \
  libmongodb-perl \
  libfreezethaw-perl \
  libclone-perl \
  libtemplate-perl \
  libclass-isa-perl
  
  
  
# R dependencies
RUN apt-get install -y r-base r-cran-nlme r-cran-ecodist r-cran-rcolorbrewer r-cran-xml && \
  echo 'install.packages("matlab", repos = "http://cran.wustl.edu")' | R --no-save && \
  echo 'source("http://bioconductor.org/biocLite.R"); biocLite("pcaMethods"); biocLite("preprocessCore"); biocLite("DESeq")' | R --no-save

# python dependencies
RUN apt-get install -y python-dev python-pip && \
  pip install \
  openpyxl==1.8.6 \
  gspread \
  xlrd \
  lepl \
  requests_toolbelt \
  cassandra-driver \
  pika

ENV PERL_MM_USE_DEFAULT 1
RUN cpan Inline::Python

