# MG-RAST v3 website

FROM mgrast/v3-base



EXPOSE 80


COPY . /MG-RAST

# v3 website
RUN cd MG-RAST && \
  make && \
  cp -rv src/MGRAST/bin/* bin/. && \
  ln -s /config/Conf.pm /MG-RAST/conf/Conf.pm && \
  cd site/CGI && \
  rm -fv api.cgi m5nr.cgi m5nr_rest.cgi

# v4-uploader for v3, only include mgmainv3.html
RUN cd / && git clone --recursive https://github.com/MG-RAST/MG-RASTv4.git && \
  cp -vr /MG-RASTv4/* /MG-RAST/site/CGI/Html/ && \
  rm -vf /MG-RAST/site/CGI/Html/*.html && \
  cp -v /MG-RASTv4/mgmainv3.html /MG-RAST/site/CGI/Html/ && \
  rm -vf /MG-RAST/site/CGI/Html/js/config.js && \
  ln -s /config/config.js /MG-RAST/site/CGI/Html/js/config.js



# setup sendmail
#RUN DEBIAN_FRONTEND=noninteractive apt-get -y install postfix && \
#  cp /usr/share/postfix/main.cf.debian /etc/postfix/main.cf && \
#  postconf -e relayhost=[smtp.mcs.anl.gov] && \
#  postconf -e myorigin=mcs.anl.gov



# symlinks for certificates (need to be in daemon home directory) and config.js
RUN ln -s /config/postgresql/ /usr/sbin/.postgresql && \
  rm -f /MG-RAST/site/CGI/Html/js/config.js && \
  ln -s /config/config.js /MG-RAST/site/CGI/Html/js/config.js

# docker run -t -i --name web -v /home/core/mgrast-config/services/web_v3/:/config -p 80:80 httpd:2.4.12 bash
# Start
# bash -c "/bin/chmod 600 /config/postgresql/*; /bin/chown daemon:daemon /config/postgresql/*; /usr/local/apache2/bin/apachectl -f /config/httpd.conf -D FOREGROUND"

