use strict;
use warnings;
no warnings qw(redefine);

1;

# this class is AUTOGENERATED and will be AUTOMATICALLY REGENERATED
# all work done in this module will be LOST


package WebComments::Comment;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		Private => [ DB_SCALAR, undef, 0, "false" ],
		User => [ DB_OBJECT, "WebServerBackend::User", 1, undef ],
		Cgi => [ DB_SCALAR, undef, 0, "" ],
		ReferenceObject => [ DB_SCALAR, undef, 1, undef ],
		Date => [ DB_SCALAR, undef, 1, undef ],
		Page => [ DB_SCALAR, undef, 0, "" ],
		Text => [ DB_SCALAR, undef, 0, "" ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
			[ "ReferenceObject", "Date" ],
			[ "ReferenceObject", "Page" ],
		];
}

1;

package WebComments::CommentDirectedAt;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		User => [ DB_OBJECT, "WebServerBackend::User", 1, undef ],
		Comment => [ DB_OBJECT, "WebComments::Comment", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
			[ "Comment", "User" ],
		];
}

1;
