#
# Top level makefile
# 
# needs some work.   :-)
#

BINSCRIPTS := makeScriptHeaders


#lib: ../Makefile
#
#../Makefile: Makefile.top
#	cp Makefile.top ../Makefile
#	@echo ""
#	@echo "A new makefile was installed; please rerun your make command."
#	@echo ""
#	@exit 1

include standard.mk
