use strict;
use warnings;
no warnings qw(redefine);

1;

# this class is AUTOGENERATED and will be AUTOMATICALLY REGENERATED
# all work done in this module will be LOST


package WebServerBackend::Preferences;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		value => [ DB_SCALAR, undef, 0, undef ],
		user => [ DB_OBJECT, "WebServerBackend::User", 0, undef ],
		application => [ DB_OBJECT, "WebServerBackend::Backend", 0, undef ],
		name => [ DB_SCALAR, undef, 0, undef ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::UserSession;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		error_page => [ DB_SCALAR, undef, 0, undef ],
		session_id => [ DB_SCALAR, undef, 1, undef ],
		error_parameters => [ DB_SCALAR, undef, 0, undef ],
		current_page => [ DB_SCALAR, undef, 0, undef ],
		timestamp => [ DB_SCALAR, undef, 1, undef ],
		previous_page => [ DB_SCALAR, undef, 0, undef ],
		user => [ DB_OBJECT, "WebServerBackend::User", 0, undef ],
		current_parameters => [ DB_SCALAR, undef, 0, undef ],
		previous_parameters => [ DB_SCALAR, undef, 0, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "session_id" ],
			[ "session_id", "user" ],
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::User;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		firstname => [ DB_SCALAR, undef, 0, undef ],
		email => [ DB_SCALAR, undef, 1, undef ],
                email2 => [ DB_SCALAR, undef, 0, undef ],
		password => [ DB_SCALAR, undef, 0, undef ],
		comment => [ DB_SCALAR, undef, 0, undef ],
		entry_date => [ DB_SCALAR, undef, 0, undef ],
		active => [ DB_SCALAR, undef, 0, "0" ],
		lastname => [ DB_SCALAR, undef, 0, undef ],
		login => [ DB_SCALAR, undef, 1, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "login" ],
			[ "email" ],
		];
}

sub indices {
     return 
		[
			[ "lastname", "firstname" ],
		];
}

1;

package WebServerBackend::OrganizationUsers;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		user => [ DB_OBJECT, "WebServerBackend::User", 0, undef ],
		organization => [ DB_OBJECT, "WebServerBackend::Organization", 0, undef ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::Scope;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		application => [ DB_OBJECT, "WebServerBackend::Backend", 0, undef ],
		name => [ DB_SCALAR, undef, 1, undef ],
		description => [ DB_SCALAR, undef, 0, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "name", "application" ],
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::Invitation;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		invitation_date => [ DB_SCALAR, undef, 1, undef ],
		email => [ DB_SCALAR, undef, 1, undef ],
		user_claimed => [ DB_OBJECT, "WebServerBackend::User", 0, undef ],
		invitation_string => [ DB_SCALAR, undef, 0, undef ],
		user_inviting => [ DB_OBJECT, "WebServerBackend::User", 1, undef ],
		claimed => [ DB_SCALAR, undef, 0, "0" ],
		scope => [ DB_OBJECT, "WebServerBackend::Scope", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::UserHasScope;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		granted => [ DB_SCALAR, undef, 0, "0" ],
		user => [ DB_OBJECT, "WebServerBackend::User", 1, undef ],
		scope => [ DB_OBJECT, "WebServerBackend::Scope", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "user", "scope" ],
		];
}

sub indices {
     return 
		[
			[ "user", "granted" ],
			[ "user", "scope" ],
		];
}

1;

package WebServerBackend::Backend;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		name => [ DB_SCALAR, undef, 1, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "name" ],
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::Rights;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		granted => [ DB_SCALAR, undef, 0, "0" ],
		data_id => [ DB_SCALAR, undef, 1, undef ],
		delegated => [ DB_SCALAR, undef, 0, "0" ],
		data_type => [ DB_SCALAR, undef, 1, undef ],
		application => [ DB_OBJECT, "WebServerBackend::Backend", 0, undef ],
		name => [ DB_SCALAR, undef, 1, undef ],
		scope => [ DB_OBJECT, "WebServerBackend::Scope", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
		];
}

sub indices {
     return 
		[
		];
}

1;

package WebServerBackend::Organization;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		country => [ DB_SCALAR, undef, 0, undef ],
		city => [ DB_SCALAR, undef, 0, undef ],
		location => [ DB_SCALAR, undef, 0, undef ],
		date => [ DB_SCALAR, undef, 0, undef ],
		url => [ DB_SCALAR, undef, 0, undef ],
		name => [ DB_SCALAR, undef, 1, undef ],
		abbreviation => [ DB_SCALAR, undef, 0, undef ],
		scope => [ DB_OBJECT, "WebServerBackend::Scope", 0, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "name" ],
		];
}

sub indices {
     return 
		[
		];
}

1;
