###################################
# this is an auto-generated package
# created by: /MG-RAST/bin/elastic_schema_parse.pl
# created on: 2017-05-04T19:30:45
###################################
package ElasticSearch;

use strict;
use warnings;
no warnings('once');

our $ontology = {
	'sample_biome' => 'biome',
	'sample_feature' => 'feature',
	'sample_material' => 'material',
	'sample_metagenome_taxonomy' => 'metagenome_taxonomy'
};

our $mixs = [
	'project_project_name',
	'sample_biome',
	'sample_feature',
	'sample_material',
	'sample_latitude',
	'sample_longitude',
	'sample_country',
	'sample_location',
	'sample_env_package',
	'sample_collection_date',
	'library_investigation_type',
	'library_seq_meth'
];

our $ids = {
	'id' => 'mgm',
	'project_project_id' => 'mgp',
	'sample_sample_id' => 'mgs',
	'library_library_id' => 'mgl',
	'env_package_env_package_id' => 'mge'
};

our $fields = {
	all => 'all',
	metagenome_id => 'id',
	sequence_type => 'job_info_sequence_type',
	created_on => 'job_info_created_on',
	job_id => 'job_info_job_id',
	mixs_compliant => 'job_info_mixs_compliant',
	public => 'job_info_public',
	name => 'job_info_name.keyword',
	bp_count_raw => 'job_stat_bp_count_raw',
	average_length_raw => 'job_stat_average_length_raw',
	drisee_score_raw => 'job_stat_drisee_score_raw',
	sequence_count_raw => 'job_stat_sequence_count_raw',
	average_gc_ratio_raw => 'job_stat_average_gc_ratio_raw',
	alpha_diversity_shannon => 'job_stat_alpha_diversity_shannon',
	project_ebi_id => 'project_project_ebi_id',
	PI_lastname => 'project_PI_lastname.keyword',
	project_funding => 'project_project_funding.keyword',
	organization_country => 'project_organization_country',
	project_name => 'project_project_name.keyword',
	organization => 'project_organization.keyword',
	lastname => 'project_lastname.keyword',
	firstname => 'project_firstname.keyword',
	PI_organization => 'project_PI_organization.keyword',
	ncbi_id => 'project_ncbi_id',
	project_id => 'project_project_id',
	greengenes_id => 'project_greengenes_id',
	PI_firstname => 'project_PI_firstname.keyword',
	PI_organization_country => 'project_PI_organization_country',
	sample_name => 'sample_sample_name.keyword',
	continent => 'sample_continent',
	collection_date => 'sample_collection_date',
	location => 'sample_location.keyword',
	elevation => 'sample_elevation',
	material => 'sample_material.keyword',
	sample_ebi_id => 'sample_sample_ebi_id',
	sample_id => 'sample_sample_id',
	country => 'sample_country',
	latitude => 'sample_latitude',
	biome => 'sample_biome.keyword',
	env_package => 'sample_env_package.keyword',
	longitude => 'sample_longitude',
	altitude => 'sample_altitude',
	depth => 'sample_depth',
	feature => 'sample_feature.keyword',
	temperature => 'sample_temperature',
	env_package_name => 'env_package_env_package_name.keyword',
	env_package_type => 'env_package_env_package_type.keyword',
	env_package_id => 'env_package_env_package_id',
	library_ebi_id => 'library_library_ebi_id',
	mrna_percent => 'library_mrna_percent',
	pubmed_id => 'library_pubmed_id',
	gold_id => 'library_gold_id',
	seq_meth => 'library_seq_meth',
	target_gene => 'library_target_gene',
	library_name => 'library_library_name.keyword',
	investigation_type => 'library_investigation_type',
	library_id => 'library_library_id',
	aa_pid => 'pipeline_parameters_aa_pid',
	assembled => 'pipeline_parameters_assembled',
	rna_pid => 'pipeline_parameters_rna_pid',
	filter_ambig => 'pipeline_parameters_filter_ambig',
	m5rna_sims_version => 'pipeline_parameters_m5rna_sims_version',
	fgs_type => 'pipeline_parameters_fgs_type',
	priority => 'pipeline_parameters_priority',
	m5nr_sims_version => 'pipeline_parameters_m5nr_sims_version',
	filter_ln => 'pipeline_parameters_filter_ln',
	screen_indexes => 'pipeline_parameters_screen_indexes',
	bowtie => 'pipeline_parameters_bowtie',
	file_type => 'pipeline_parameters_file_type',
	filter_ln_mult => 'pipeline_parameters_filter_ln_mult',
	pipeline_version => 'pipeline_parameters_pipeline_version',
	prefix_length => 'pipeline_parameters_prefix_length',
	m5nr_annotation_version => 'pipeline_parameters_m5nr_annotation_version',
	max_ambig => 'pipeline_parameters_max_ambig',
	dereplicate => 'pipeline_parameters_dereplicate',
	m5rna_annotation_version => 'pipeline_parameters_m5rna_annotation_version',
};

our $prefixes = {
	'job_info_' => [
		'sequence_type',
		'created_on',
		'job_id',
		'mixs_compliant',
		'public',
		'name',
	],
	'job_stat_' => [
		'bp_count_raw',
		'average_length_raw',
		'drisee_score_raw',
		'sequence_count_raw',
		'average_gc_ratio_raw',
		'alpha_diversity_shannon',
	],
	'project_' => [
		'project_ebi_id',
		'PI_lastname',
		'project_funding',
		'organization_country',
		'project_name',
		'organization',
		'lastname',
		'firstname',
		'PI_organization',
		'ncbi_id',
		'project_id',
		'greengenes_id',
		'PI_firstname',
		'PI_organization_country',
	],
	'sample_' => [
		'sample_name',
		'continent',
		'collection_date',
		'location',
		'elevation',
		'material',
		'sample_ebi_id',
		'sample_id',
		'country',
		'latitude',
		'biome',
		'env_package',
		'longitude',
		'altitude',
		'depth',
		'feature',
		'temperature',
	],
	'env_package_' => [
		'env_package_name',
		'env_package_type',
		'env_package_id',
	],
	'library_' => [
		'library_ebi_id',
		'mrna_percent',
		'pubmed_id',
		'gold_id',
		'seq_meth',
		'target_gene',
		'library_name',
		'investigation_type',
		'library_id',
	],
	'pipeline_parameters_' => [
		'aa_pid',
		'assembled',
		'rna_pid',
		'filter_ambig',
		'm5rna_sims_version',
		'fgs_type',
		'priority',
		'm5nr_sims_version',
		'filter_ln',
		'screen_indexes',
		'bowtie',
		'file_type',
		'filter_ln_mult',
		'pipeline_version',
		'prefix_length',
		'm5nr_annotation_version',
		'max_ambig',
		'dereplicate',
		'm5rna_annotation_version',
	],
};

our $types = {
	metagenome_id => 'keyword',
	sequence_type => 'keyword',
	created_on => 'date',
	job_id => 'integer',
	mixs_compliant => 'boolean',
	public => 'boolean',
	name => 'text',
	bp_count_raw => 'long',
	average_length_raw => 'float',
	drisee_score_raw => 'float',
	sequence_count_raw => 'integer',
	average_gc_ratio_raw => 'float',
	alpha_diversity_shannon => 'float',
	project_ebi_id => 'keyword',
	PI_lastname => 'text',
	project_funding => 'text',
	organization_country => 'keyword',
	project_name => 'text',
	organization => 'text',
	lastname => 'text',
	firstname => 'text',
	PI_organization => 'text',
	ncbi_id => 'keyword',
	project_id => 'keyword',
	greengenes_id => 'keyword',
	PI_firstname => 'text',
	PI_organization_country => 'keyword',
	sample_name => 'text',
	continent => 'keyword',
	collection_date => 'date',
	location => 'text',
	elevation => 'float',
	material => 'text',
	sample_ebi_id => 'keyword',
	sample_id => 'keyword',
	country => 'keyword',
	latitude => 'float',
	biome => 'text',
	env_package => 'text',
	longitude => 'float',
	altitude => 'float',
	depth => 'float',
	feature => 'text',
	temperature => 'float',
	env_package_name => 'text',
	env_package_type => 'text',
	env_package_id => 'keyword',
	library_ebi_id => 'keyword',
	mrna_percent => 'float',
	pubmed_id => 'keyword',
	gold_id => 'keyword',
	seq_meth => 'keyword',
	target_gene => 'text',
	library_name => 'text',
	investigation_type => 'keyword',
	library_id => 'keyword',
	aa_pid => 'integer',
	assembled => 'boolean',
	rna_pid => 'integer',
	filter_ambig => 'boolean',
	m5rna_sims_version => 'integer',
	fgs_type => 'keyword',
	priority => 'keyword',
	m5nr_sims_version => 'integer',
	filter_ln => 'boolean',
	screen_indexes => 'keyword',
	bowtie => 'boolean',
	file_type => 'keyword',
	filter_ln_mult => 'float',
	pipeline_version => 'keyword',
	prefix_length => 'integer',
	m5nr_annotation_version => 'integer',
	max_ambig => 'integer',
	dereplicate => 'boolean',
	m5rna_annotation_version => 'integer',
};

1;
