###################################
# this is an auto-generated package
# created by: /MG-RAST/bin/elastic_schema_parse.pl
# created on: 2017-05-01T20:43:08
###################################
package MGRAST::ElasticSearch;

use strict;
use warnings;
no warnings('once');

our $fields = {
	all => 'all',
	metagenome_id => 'id',
	mixs_compliant => 'job_info_mixs_compliant',
	seq_method => 'job_info_seq_method',
	version => 'job_info_version',
	job_id => 'job_info_job_id',
	public => 'job_info_public',
	name => 'job_info_name.keyword',
	pipeline_version => 'job_info_pipeline_version',
	sequence_type => 'job_info_sequence_type',
	created => 'job_info_created',
	alpha_diversity => 'job_stat_alpha_diversity',
	sequence_count => 'job_stat_sequence_count',
	bp_count => 'job_stat_bp_count',
	average_gc_ratio => 'job_stat_average_gc_ratio',
	average_length => 'job_stat_average_length',
	drisee_score => 'job_stat_drisee_score',
	project_id => 'project_project_id',
	PI_organization => 'project_PI_organization.keyword',
	organization_country => 'project_organization_country',
	ncbi_id => 'project_ncbi_id',
	project_funding => 'project_project_funding.keyword',
	PI_organization_country => 'project_PI_organization_country',
	organization => 'project_organization.keyword',
	firstname => 'project_firstname.keyword',
	lastname => 'project_lastname.keyword',
	PI_firstname => 'project_PI_firstname.keyword',
	project_name => 'project_project_name.keyword',
	PI_lastname => 'project_PI_lastname.keyword',
	all => 'project_all',
	sample_name => 'sample_sample_name.keyword',
	biome => 'sample_biome',
	depth => 'sample_depth',
	env_package_all => 'sample_env_package_all',
	collection_date => 'sample_collection_date',
	continent => 'sample_continent',
	latitude => 'sample_latitude',
	env_package_id => 'sample_env_package_id',
	country => 'sample_country',
	longitude => 'sample_longitude',
	sample_all => 'sample_sample_all',
	material => 'sample_material.keyword',
	env_package_name => 'sample_env_package_name',
	location => 'sample_location.keyword',
	altitude => 'sample_altitude',
	sample_id => 'sample_sample_id',
	temperature => 'sample_temperature',
	elevation => 'sample_elevation',
	feature => 'sample_feature.keyword',
	env_package_type => 'sample_env_package_type',
	library_id => 'library_library_id',
	all => 'library_all.keyword',
	library_name => 'library_library_name.keyword',
	pubmed_id => 'library_pubmed_id',
	gold_id => 'library_gold_id',
	m5nr_sims_version => 'pipeline_parameters_m5nr_sims_version',
	screen_indexes => 'pipeline_parameters_screen_indexes',
	rna_pid => 'pipeline_parameters_rna_pid',
	m5nr_annotation_version => 'pipeline_parameters_m5nr_annotation_version',
	aa_pid => 'pipeline_parameters_aa_pid',
	bowtie => 'pipeline_parameters_bowtie',
	m5rna_sims_version => 'pipeline_parameters_m5rna_sims_version',
	filter_ln => 'pipeline_parameters_filter_ln',
	m5rna_annotation_version => 'pipeline_parameters_m5rna_annotation_version',
	fgs_type => 'pipeline_parameters_fgs_type',
	priority => 'pipeline_parameters_priority',
	prefix_length => 'pipeline_parameters_prefix_length',
	dereplicate => 'pipeline_parameters_dereplicate',
	filter_ln_mult => 'pipeline_parameters_filter_ln_mult',
	max_ambig => 'pipeline_parameters_max_ambig',
	file_type => 'pipeline_parameters_file_type',
	filter_ambig => 'pipeline_parameters_filter_ambig',
	assembled => 'pipeline_parameters_assembled',
};

our $types = {
	metagenome_id => 'keyword',
	mixs_compliant => 'boolean',
	seq_method => 'keyword',
	version => 'integer',
	job_id => 'integer',
	public => 'boolean',
	name => 'text',
	pipeline_version => 'keyword',
	sequence_type => 'keyword',
	created => 'date',
	alpha_diversity => 'float',
	sequence_count => 'integer',
	bp_count => 'long',
	average_gc_ratio => 'float',
	average_length => 'float',
	drisee_score => 'float',
	project_id => 'keyword',
	PI_organization => 'text',
	organization_country => 'keyword',
	ncbi_id => 'keyword',
	project_funding => 'text',
	PI_organization_country => 'keyword',
	organization => 'text',
	firstname => 'text',
	lastname => 'text',
	PI_firstname => 'text',
	project_name => 'text',
	PI_lastname => 'text',
	all => 'text',
	sample_name => 'text',
	biome => 'keyword',
	depth => 'float',
	env_package_all => 'text',
	collection_date => 'date',
	continent => 'keyword',
	latitude => 'float',
	env_package_id => 'keyword',
	country => 'keyword',
	longitude => 'float',
	sample_all => 'text',
	material => 'text',
	env_package_name => 'keyword',
	location => 'text',
	altitude => 'float',
	sample_id => 'keyword',
	temperature => 'float',
	elevation => 'float',
	feature => 'text',
	env_package_type => 'keyword',
	library_id => 'keyword',
	all => 'text',
	library_name => 'text',
	pubmed_id => 'keyword',
	gold_id => 'keyword',
	m5nr_sims_version => 'integer',
	screen_indexes => 'keyword',
	rna_pid => 'integer',
	m5nr_annotation_version => 'integer',
	aa_pid => 'integer',
	bowtie => 'boolean',
	m5rna_sims_version => 'integer',
	filter_ln => 'boolean',
	m5rna_annotation_version => 'integer',
	fgs_type => 'keyword',
	priority => 'keyword',
	prefix_length => 'integer',
	dereplicate => 'boolean',
	filter_ln_mult => 'float',
	max_ambig => 'integer',
	file_type => 'keyword',
	filter_ambig => 'boolean',
	assembled => 'boolean',
};

1;
